src/datatype.rs, src/environment.rs
This PR carrys forward successful compilation of `rsmpi` on nightly.
=> Fix useless_transmute warnings by clippy on nightly

src/collective.rs, src/datatype.rs, src/environment.rs, src/point_to_point.rs, src/request.rs, src/topology.rs
Use of extern static variables will be treated as unsafe code by rustc in the future.
This change makes rsmpi able to be compiled on the nightly as of Oct/1, 2016.
Edit: Sorry. This PR sucks because it makes rsmpi unable to be compiled on the stable due to unnecessary unsafes. Please just close it or keep it for the future.
=> Mark use of extern static variables unsafe

build.rs, examples/buffered.rs, examples/immediate.rs, examples/immediate_all_gather.rs, examples/immediate_all_gather_varcount.rs, examples/immediate_all_to_all.rs, examples/immediate_broadcast.rs, examples/immediate_gather.rs, examples/immediate_gather_varcount.rs, examples/immediate_reduce.rs, examples/immediate_scan.rs, examples/immediate_scatter.rs, examples/immediate_scatter_varcount.rs, examples/readme.rs, examples/ready_send.rs, src/collective.rs, src/lib.rs, src/point_to_point.rs, src/request.rs
Created two kinds of `Scope` objects:
- `LocalScope` to track `Request`s with arbitrary lifetime `'a`
- `StaticScope` (no bookkeeping, but only `'static` `Request`s)
The `Request` trait has been squashed into a single `Request<S>` data type, where `S` is the type of scope that this `Request` is associated with.
Fixes #17.
---
- ~~It would be nice to generalize `Buffer` to allow things like `Rc`, which would be compatible with `StaticScope`.~~ (WIP: https://github.com/bsteinb/rsmpi/compare/Rufflewind:bindgen-hack...Rufflewind:buffer)
=> Simplify and make Request safer

src/collective.rs, src/topology.rs
The `!` type informs Rust that any code that follows is unreachable, which is useful because the user is no longer obligated to return anything afterward.  To do this, `process::abort()` was added to `MPI_Abort`.  It also makes sure the program dies even if `MPI_Abort` doesn’t kill the program (which shouldn't ever happen).
=> Make abort return !

.travis.yml, Cargo.toml, examples/immediate_reduce.rs, examples/immediate_scan.rs, examples/reduce.rs, src/collective.rs, src/datatype.rs, src/lib.rs
It’s not pretty …  Because of how MPI_User_function is defined, it doesn’t give us a clean way attach/access arbitrary user data.  As a result, we have to pull in libffi to hack our way through.
- Add `BorrowedDatatype`, a thin wrapper over `MPI_Datatype` (feel free to bikeshed on the name)
- Redefine `SystemDatatype = BorrowedDatatype<'static>`
- Add `DynBuffer[Mut]`
- Add `is_commutative`
- Add `UserOperation`
=> Add support for user-defined operations

examples/all_gather_bool.rs, src/datatype.rs, src/ffi/rsmpi.c, src/ffi/rsmpi.h
Since the Rust team [committed to](https://github.com/rust-lang/rust/pull/46176#issuecomment-359593446) ABI compatibility between Rust's `bool` and C's `_Bool`, I've added a mapping from bool to ffi::RSMPI_C_BOOL.
Addresses issue #34.
=> Add RSMPI_C_BOOL as the equivalent_system_datatype for bool

.travis.yml, mpi-sys/src/lib.rs, mpi-sys/src/rsmpi.c, mpi-sys/src/rsmpi.h
OpenMPI does not have a typedef for MPI_Fint - added RSMPI_Fint.
MPICH uses macros for c2f - Export a C ABI for these routines (e.g. RSMPI_Comm_c2f).
Addresses #39 .
=> Export stable ABI for c2f

README.md, build-probe-mpi/Cargo.toml, build-probe-mpi/src/lib.rs, build-probe-mpi/src/os/mod.rs, build-probe-mpi/src/os/unix.rs, build-probe-mpi/src/os/windows.rs, build.rs, examples/immediate_reduce.rs, examples/reduce.rs, examples/split.rs, mpi-sys/Cargo.toml, mpi-sys/build.rs, src/collective.rs, src/topology.rs
This commit adds support for the MS-MPI implementation, primarily targeting Windows. I add some code to discover for MS-MPI that only run on Windows, and moved the other MPI probing to a separate probe function for Unix.
I inject an msmpi cfg into both mpi-sys and rsmpi. This may be useful to either surface msmpi specifically functionality or, like I do in this commit, to disable certain features that are missing from MS-MPI.
I noticed two issues when building with the MS-MPI headers:
1. MPI_Comm_create_group was missing.
2. Bindgen does not seem to pick up the MPI_User_function definition
For both of these issues, I just removed the APIs that called these functions when using MS-MPI. This may not be the best method.
I also disabled portions of any tests that rely on these …
=> Support for MS-MPI and Windows

examples/complex_datatype.rs, examples/datatype_dup.rs, examples/structured.rs, src/datatype.rs, src/raw.rs
- Adds new types: `UncommittedUserDatatype` + `UncommittedDatatypeRef`
- same constructors as `UserDatatype` and `DatatypeRef`
- `UncommittedUserDatatype::commit` consumes the old value to produce a `UserDatatype`
- `UserDatatype::structured` and `UncommittedUserDatatype::structured` constructors takes a slice that can be passed directly to underlying `MPI_Type_create_struct` call without copy
- new `as_ref()` functions for `UserDatatype` and `UncommittedUserDatatype`
- Adds `UncommittedDatatype` trait
- Implemented for all Datatype types
- Supports capability for duplicating the datatype
- `From` implemented for Datatype types to allow downcasting of heterogeneous types when being mixed into a single contiguous array. Utility demonstrated by `bool::equivalent_datatype().into()` in …
=> Enhancements to mpi::datatype

examples/pack.rs, src/datatype.rs, src/topology.rs
Note: I'm unsure if `unpack()` needs to be unsafe. It's unclear to me that, if the typemap of the datatype is incompatible with the buffer being provided to `MPI_Unpack`, if that results in memory unsafety. I don't *think* it does, but may need another eye on this.
=> Support packing and unpack data to byte buffers

.travis.yml, README.md, ci/install-mpi-windows.sh, ci/run-examples.sh, examples/env_inq.rs, examples/immediate_barrier.rs
This change enables Travis CI to run with MS-MPI on Windows. It disables a couple tests that do not pass with MS-MPI.
=> Run Travis CI on Windows

src/datatype.rs
=> MPI_Type_hvector (Removed in MPI-3) -> MPI_Type_create_hvector

Cargo.toml, mpi-sys/Cargo.toml
Changes the `libffi` dependency to version `0.7.0` instead of pinning it at `0.6.4` which was yanked due to `bindgen` version issues (see #68 and [tov/libffi-sys-rs#21](https://github.com/tov/libffi-sys-rs/issues/21)). Fixes #69 on my system, the [latest Travis CI failures](https://travis-ci.org/bsteinb/rsmpi/builds/533988480), and closes #68.
Since the change is semver-incompatible due to `bindgen`, the `mpi` crate versions were also bumped to `0.6.0` for `mpi` and `0.2.0` for `mpi-sys`.
=> fix libffi pinning and bump crate versions

Cargo.toml, examples/immediate.rs, src/collective.rs, src/datatype.rs, src/environment.rs, src/lib.rs, src/point_to_point.rs, src/request.rs, src/topology/cartesian.rs, src/topology/mod.rs
I want to add some async await features, so I upgraded to rust 2018 edition to support this. Async await changes will come in a separate PR.
I mostly just ran `cargo fix --edition` and `cargo fmt`, then changed a few "use" statements to use `crate::`.
=> Switch to rust 2018

examples/wait_any.rs, src/request.rs
I needed the MPI_Waitany for a personal project so I decided to implement it as a function in the Request module. This is the first time i work with ffi and unsafe code so I tried to keep things as simple as possible.
I'm not sure if using a Vec of Request as input parameter and removing the completed Request from it is the best way to go but it was the simplest I could find.
=> Implemented MPI_Waitany

src/request.rs
=> Terminate execution when scoped requests are leaked.

Cargo.toml, build.rs, src/collective.rs, src/datatype.rs, src/environment.rs, src/lib.rs, src/point_to_point.rs, src/request.rs, src/topology/mod.rs
This was created using regex-based mass-replacement of the now obsolete `unsafe_extern_static` macro.
=> Drop obsolete unsafe_extern_static macro

.travis.yml, Cargo.toml, build-probe-mpi/src/os/windows.rs, build.rs, examples/immediate_reduce.rs, examples/reduce.rs, mpi-sys/Cargo.toml, mpi-sys/build.rs, src/collective.rs
As of the "0.9.0" release of the libffi crate, Windows and Mac are now supported. Additionally, in "1.0.0", bindgen is no longer used by libffi, which means we can now update our version of the dependency.
In order to avoid surprising people with the "0.6" release, this makes "user-operations" a default feature again since it now has wider support.
Improved behavior in the "0.55" release of bindgen gets rid of the weird hacks that had to be done for MS-MPI.
cc @adamreichold @bsteinb
=> Update libffi, bindgen, and restore user-operations as a default feature

examples/struct.rs, mpi-derive/src/lib.rs, src/collective.rs, tests/derive_tests.rs
Allows the derive macro to be used on static arrays with non `{integer}`
type constants, Specifically, `usize`. I include a test to prevent
regression.
I made 2 cosmetic changes in collective.rs and examples/struct.rs to
allow `rsmpi` to compile without warnings.
=> Fix derive Equivalence for arrays + formatting

examples/broadcast.rs, examples/scatter.rs, examples/send_receive.rs, src/datatype.rs
To allow `&vec` instead of `vec.as_slice()`.
=> Implement Buffer and BufferMut for Vec

src/topology/mod.rs, tests/trait_object_safety_test.rs
This PR makes the `Communicator` and `Group` traits "object safe," it will allow you to write things like:
```rust
fn foo(comm: &dyn Communicator) { }
fn bar(gp: &dyn Group) { }
```
fixes #108
=> Make `Communicator` and `Group` traits "object safe"

Cargo.toml, build-probe-mpi/Cargo.toml, build-probe-mpi/src/lib.rs, build-probe-mpi/src/os/unix.rs, build-probe-mpi/src/os/windows.rs, mpi-sys/Cargo.toml, mpi-sys/build.rs
This is tested with `PrgEnv-aocc` on [NERSC Perlmutter](https://www.nersc.gov/systems/perlmutter/). It detects the environment and finds it by default based on `CRAY_MPICH_DIR`. It did not work with `PngEnv-cray`, but I think thsi needs to be fixed in [clang-sys](https://github.com/KyleMayes/clang-sys/issues/143). I expect it will work with upstream clang on Cray.
I also fixed some incomplete propagation of `mpicc` and include paths that previously caused `rsmpi.c` to be compiled using default paths, and thus fail or build for the wrong MPI when intending to use a non-default MPI.
@skailasa or @tbetcke Would you be able to test this on one of your systems?
=> Improve pkg-config detection and support Cray

build-probe-mpi/src/lib.rs, examples/immediate.rs, examples/immediate_barrier_multiple.rs, examples/immediate_multiple_barrier.rs, examples/immediate_multiple_requests.rs, examples/immediate_multiple_test.rs, src/collective.rs, src/lib.rs, src/point_to_point.rs, src/request.rs
Hello, I've been working with @hppritcha to attempt adding multiple request completion support. This is partly based on @AndrewGaspar's original PR #36 but is slightly different. Based on some of the discussion in #29, I experimented with attaching references to each request as a way to allow the user to immediately perform some computation on the data as soon as the request has been waited on.
Using the modified request object as a basis I added a RequestCollection object, similar to the former PR, but including support for attached references. Requests can be added to the collection and then waited on using the wait_*() or test_*() methods. To ensure that requests have completed, I included a new `multiple_scope()` function which passes in both a reference to a scope object and a …
=> Multiple Request Completion 2

.github/workflows/test.yaml
This should fix the intermittent test failures on OSX.
https://github.com/open-mpi/ompi/issues/7393
=> actions: workaround for TMPDIR truncation with OMPI on OSX

README.md
As suggested in #118 I have created a documentation link to an example project that uses mpi4py with rsmpi. If there are more example bindings to other langauges this may move into a subdirectory of rsmpi. But given there is only one example it might be easiest to just add a documentation link for now.
=> Add documentation link to example project for using rsmpi with mpi4py

.github/workflows/test.yaml
Choco with --version 14.0.6 errors with the following. It seems more important to test newer versions than to pin to an old version (and I'd rather not expand the matrix) so we can keep the install but accept the default version.
Failures
- llvm - A newer version of llvm (v15.0.5) is already installed. Use --allow-downgrade or --force to attempt to install older versions, or use --side-by-side to allow multiple versions.
=> CI: allow default llvm in Windows

examples/immediate_multiple_test.rs, examples/struct.rs, src/collective.rs, src/environment.rs, src/topology/cartesian.rs, src/topology/mod.rs
As outlined in #148, it is very unintuitive to split the Communicator interface in `SystemCommunicator` and `UserCommunicator`.
I drafted a PR to unify both into one common `enum SimpleCommunicator`:
- I migrated topology-related code from UserCommunicator into the common enum, so both communicator variants can now call those functions. I couldn't confirm it outright, but the spec does not prohibit that explicitely, so I think this models the MPI interface more closely.
- I refactored CartesianCommunicator to accept both World- and UserCommunicator, which is legal by spec, I don't know why this wasn't possible before.
- since WorldCommunicator is no longer Copy, code that moved a reference to SystemCommunicator must now explicitly refer to IntraCommunicator::WorldCommunicator (see …
=> Remove type-distinction between system-communicators and user-communicators

CHANGELOG.md, examples/attributes.rs, examples/complex_numbers.rs, examples/derive_multiple_thread_init.rs, examples/derive_nonthreaded_panic.rs, examples/derive_postfinalize_panic.rs, examples/derive_preinit_panic.rs, examples/spawn.rs, examples/spawn_multiple.rs, examples/struct.rs, src/attribute.rs, src/environment.rs, src/lib.rs, src/topology/mod.rs
Attributes now hide the keys from most user code, and are easy to implement for new types. The current implementation still does not support setting/getting attributes on `dyn Communicator`.
=> Refactor attributes and add support for setting

examples/structured.rs, src/topology/mod.rs
* Bug/confusion introduced here: https://github.com/rsmpi/rsmpi/pull/157/files#r1462677040
* Process now holds AnyProcess and returns reference to it in as_communicator()
* Fix denied warning in examples/structured.rs and make more strict
* AnyProcess is now Copy and Clone, like Process
* Add Process::is_self() for common pattern
=> Fix process.as_communicator().rank() and examples/structured

CHANGELOG.md, Cargo.toml, build-probe-mpi/Cargo.toml, examples/immediate.rs, examples/ready_send.rs, mpi-derive/Cargo.toml, mpi-sys/Cargo.toml, src/collective.rs, src/point_to_point.rs
As discussed in #182, ready mode can't practically be used safely. Here we make it unsafe and add comments explaining the issues.
=> Ready mode is unsafe

build.rs, examples/struct.rs, mpi-sys/build.rs
https://blog.rust-lang.org/2024/05/06/check-cfg.html#buildrs-example
Remove rustc-cfg=msmpi from mpi-sys since the code doesn't use it.
=> Declare cfg(msmpi) to avoid warnings with 1.80 onward

mpi-sys/build.rs
When using MPICH, all the MPI opaque types are typedef'd to int so they can be mixed up without the type checker noticing. This leads to silent bugs when using MPICH (or MSMPI, etc.) that would be compilation errors with Open MPI. Bindgen's new_type_alias() wraps those arguments in newtypes to obtain stricter type checking.
=> mpi-sys: bindgen: use new_type_alias for opaque types

src/lib.rs
At some point the links to mpi-forum.org broke - this PR simply changes two links to the page they originally pointed to in order to fix a 404 error.
=> MPI-forum.org links have moved, update links in this project

.github/workflows/test.yaml, README.md, build-probe-mpi/src/lib.rs, build-probe-mpi/src/os/windows.rs, ci/install-mpi-windows.sh
This PR is related to issue #204
This pull request includes several changes to the GitHub Actions workflows, documentation, and code related to MPI (Message Passing Interface) support. The most important changes involve updating the MPI packages used in the workflows, improving support for different MPI implementations on Windows, and fixing a typo in the code.
* [`.github/workflows/test.yaml`](diffhunk://#diff-245392b692a50c38ecab4381b118862db514035c10983f3bd4f4b7f1f4be4692L23-R71):  Added support for `intelmpi` on Windows.
* [`ci/install-mpi-windows.sh`](diffhunk://#diff-e8612bf247b5ea5fde5483d3e7528c5d8c9566adddd4c7b9a2a17f3b424b6ec2L1-L15): Update the script for installing MS-MPI on Windows, it will now handle intel MPI and MS-MPI
* …
=> Add support for Intel MPI on Windows 
